### PR TITLE
fix #79, define a new greptype bsd to select : seperator

### LINKED ISSUE #79: bsd grep: panic when trying to split a matched string
for a specific string
`./pack/plugins/start/vim-go/ftplugin/gomod.vim:13:      \ | exe 'au! vim-go-gomod-buffer * <buffer>'"`
the splitting here doesn't work
https://github.com/vrothberg/vgrep/blob/9cc36833073ac6cae33dabdf87c92fcc3910cd90/vgrep.go#L251-L257
it fails and causes an index out of range error at line 256, because it didn't split into 3 parts
but only 1, lenght of spl is just 1
I added some print statements and this is the output
```bash
╰─➤  go run ~/go/src/github.com/vrothberg/vgrep/vgrep.go vim-go                                                                                    1 ↵
----------------Debugging------------------
>>> before split:
./pack/plugins/start/vim-go/ftplugin/gomod.vim:13:      \ | exe 'au! vim-go-gomod-buffer * <buffer>'"
>>> after splitting:
0 | ./pack/plugins/start/vim-go/ftplugin/gomod.vim:13:      \ | exe 'au! vim-go-gomod-buffer * <buffer>'"
----------------Debugging------------------
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.(*vgrep).splitMatch(0xc00005a240, 0xc000126000, 0x76, 0xc000140000, 0x11bce25, 0x32, 0xc000142000, 0x2e5, 0x2e6, 0x0)
        /Users/sjangra/go/src/github.com/vrothberg/vgrep/vgrep.go:264 +0x7ca
main.(*vgrep).grep(0xc00005a240, 0xc00004e540, 0x1, 0x1)
        /Users/sjangra/go/src/github.com/vrothberg/vgrep/vgrep.go:233 +0x308
main.main()
        /Users/sjangra/go/src/github.com/vrothberg/vgrep/vgrep.go:105 +0x46e
exit status 2
```
When it works successfully, debug output looks like this, for comparison
```
----------------Debugging------------------
>>> before split:
lruCache.go145func (cache *LRUCache) write(key string, data interface{}) (qdata, error) {
>>> after splitting:
0 | lruCache.go
1 | 145
2 | func (cache *LRUCache) write(key string, data interface{}) (qdata, error) {
----------------Debugging------------------
Index File        Line Content
    0 lru.go         9 cache := new(LRUCache)
    1 lruCache.go   23 type LRUCache struct {
    2 lruCache.go  107 func (cache *LRUCache) init(capacity int) {
    3 lruCache.go  112 func (cache *LRUCache) read(key string) (interface{}, error) {
    4 lruCache.go  125 func (cache *LRUCache) touch(key string) error {
    5 lruCache.go  145 func (cache *LRUCache) write(key string, data interface{}) (qdata, error) {
```

### PR DESCRIPTION
**Pull request by mojozinc**
based on the grep type select the seperator
and splitting format in splitMatch function

https://github.com/vrothberg/vgrep/issues/79

### CODE REVIEW

**Comment by mojozinc** [comment]
This fix is basically 2 changes:
1. check if the grep being used is a BSD grep, 
2. splitMatch splits the matched string based on the type of grep,

regarding 1, I am guessing we are on the same page, i.e parsing stdout. if there is a better way let me know. 
and for 2. now that we have 4 types of grep's switch seemed more apt,

File: vgrep.go [hunk 1]
```diff
@@ -243,18 +254,27 @@ func (v *vgrep) grep(args []string) {
...
-	spl := bytes.SplitN([]byte(match), []byte{0}, 3)
-	if gitgrep && !ripgrep {
-		return string(spl[0]), string(spl[1]), string(spl[2])
-	}
-	// the 2nd separator of grep is ":"
-	splline := bytes.SplitN(spl[1], []byte(":"), 2)
-	return string(spl[0]), string(splline[0]), string(splline[1])
+	var seperator []byte
+	switch greptype {
+	case "BSD":
```
Comment (vrothberg) [inline vgrep.go:264]: Could we add consts for the strings?
``` golang
const (
 BSDGrep = "BSD"
 GNUGrep = "GNU"
...
)
```

Comment (mojozinc) [reply vgrep.go]: makes sense 👍 
done.
